### ISSUE TITLE
[Feature Request] Better JSON API Support

### ISSUE THREAD

**Issue by vinkla** [thephpleague/fractal#187]
Since JSON-API has released their "stable" version `1.0` of the standard we should start implementing it. I know there has been some discussions about adding this but I thinks it would be good to have this in its own issue as well. What can we do to speed up this process?

**What we need to do:**
- [ ] Add links
- [ ] Add relationships
- [ ] Always set `data` as resource key
- [ ] Rename `includes` to `included`
- [ ] Included resources should be moved outside the `data` object
- [ ] All resources should return `id`, `type` and `attributes`

Please correct the todos if I've messed up. Thanks.

**Comment by dbbk** [comment]
Any movement on this?

**Comment by cmosguy** [comment]
Yeah I'm trying to figure out what still needs to be implemented in order to make the responses 1.0 compatible?

**Comment by benplummer** [comment]
It could be useful if we make a public list of the crucial points for JSON API 1.0 that Fractal should follow, that we can update. Maybe a Gist? Any ideas?

**Comment by romainprevost** [comment]
There is a package that fully implement JSON API 1.0 on github: https://github.com/neomerx/json-api, could be a starting point ?

**Comment by vinkla** [comment]
Yeah and also https://github.com/tobscure/json-api

**Comment by philsturgeon** [comment]
> Works with version 1.0 RC3 of the spec.

Watch out for the differences between RC versions and v1.0-final. 

This packages half-attempt at JSON-API support was RC1, if that. Looking at the changes will be the first step.

**Comment by vinkla** [comment]
@philsturgeon Thanks for the heads up. 

There doesn't seem to be any changelog for JSON API changes anywhere. They haven't tagged their pre-releases either. Does anyone know if there even exists a changelog somewhere?

**Comment by cmosguy** [comment]
Did you guys notice the link that @romainprevost sent: https://github.com/neomerx/json-api 

If you notice, they use a sample application that uses "Schemas": https://github.com/neomerx/json-api/tree/master/sample, which is a twist on the Fractal's Transformer design pattern.  Food for thought.  Hopefully, someone gets something working soon for JSON-API 1.0.

**Comment by andreygrehov** [comment]
+1

**Comment by lukasoppermann** [comment]
Would really appreciate this, any news?

**Comment by frozzare** [comment]
+1

**Comment by magnus-bergman** [comment]
+1

**Comment by vinkla** [comment]
I've added some todos to the first comment: https://github.com/thephpleague/fractal/issues/187#issue-84428107

**Comment by lucadegasperi** [comment]
+1

**Comment by philsturgeon** [comment]
Can we cool it on the +1's? JSON-API support is important, but spamming people with email notifications wont get the job done. :)

**Comment by cmosguy** [comment]
Is there a JSON-API validator somewhere?  It would be so cool if there was something that we could validate our API against.  I guess manually coding a behat TDD test with the examples from jsonapi.org my work to, but just curious.

**Comment by jackweinbender** [comment]
So, how much work do we imagine the serializer doing? As I've been thinking through how I might tackle this problem, it occurred to me that the location of the "seam" between the transformer and the serializer is problematic for implementing JSON-API. Do we imagine the transformer only dealing with the `attributes` of the main payload? It seems the `links` and `meta` could also be addressed in the transformer, but relationships are more difficult. The current setup simply tacks-on the `includes` after the main payload within the Scope's `toArray` method (which worked perfectly for traditional side loading); but JSON-API requires the `related` reference objects to be nested in the main payload. So, I guess the short version is that where ever we deal with the relationships, we need to have access to the main payload too, which, in its current incarnation, means the Transformer, rather than the Serializer. 

Have I missed or misunderstood anything?

**Comment by catalinux** [comment]
My version of something similar to JsonApi was done using
- a Transformer class that transforms the model into a node with attributes, type, id fields
- a custom Serializer that extends the JsonApiSerializer, overriding item, collection, includedata - most of the changes are about the "resource key", and also mergeIncludes that will generate relationships for each node

**Comment by bencromwell** [comment]
So should the Serializer simply look for an ID field provided by the transformer and assume every other field is an attribute? The type would have to come from manipulating the Transformer's class name.

Or add an interface that defines a `JsonApiSerializableContract` for use in the Transformers that provides getters for the ID and type, and treat the result of the normal `transform` as being the attributes?

Perhaps take both approaches and if there's no interface on the transformer it would attempt to figure out what it needs as per the first possibility?

I'm not sure about the latter but at least an interface could be ignored by Serializers that don't need it.

**Comment by jackweinbender** [comment]
Links too—that's not a bad idea.

**Comment by Art4** [comment]
@cmosguy I'm building a JSON API client that can be used as a validator. My first goal for release 0.1 is to fit the JSON API spec 100%. Still WIP.

https://github.com/Art4/json-api-client

**Comment by lukasoppermann** [comment]
Hey, will this include error objects as well?

**Comment by defenestrator** [comment]
@lukasoppermann It damn well better, since the specification MUST respond with either data or error in the top level document and they MUST NOT co-exist in the same document . http://jsonapi.org/format/#document-top-level

I may take a crack at this, because I would like to see it supported as well.

**Comment by lukasoppermann** [comment]
@defenestrator awesome, thanks for working on it.

**Comment by defenestrator** [comment]
@jackweinbender - have you made any progress on this? I read through your comment, and looking at the source I see what you're saying. I'm going to dig into this over the next week because I like this package and I like json API. That's right, I like your package, @philsturgeon 

@bencromwell I like the idea of an interface, that was my thought out of the gate. In fact I'm not seeing another idea in my mind that I find viable. Will look at some of the existing php json:api implementations linked above for a better understanding, but I'd really like to see this done. Anyone out there making progress?

**Comment by philsturgeon** [comment]
As a heads up, @jasonlewis and @willishq have both taken over this package, and will continue with the plans I had for v1.0, including general code improvements but JSON-API support as a primary goal.

Don't worry about hacking it into v0.12 or trying to make a v0.13, because these two are gonna sort it out properly. 

It might be worth waiting to see what they say before getting too involved with submitting any code.

**Comment by defenestrator** [comment]
I hadn't noticed because the League site still says it is all your fault. Thanks, Phil.

**Comment by philsturgeon** [comment]
Not as of a few hours ago it doesn’t https://github.com/thephpleague/thephpleague.github.io/pull/59

**Comment by defenestrator** [comment]
Very well then. Ass. :japanese_ogre: Haha

**Comment by jackweinbender** [comment]
@defenestrator I've cobbled together my own implementation for the interim (tightly integrated with me Framework; tisk, tisk). However, it looks like some other folks have a PR ready for much of the functionality (https://github.com/thephpleague/fractal/pull/205). I'm not sure what's holding up the merge.

**Comment by neomerx** [comment]
If thephpleague is OK to add my JSON-API package (JSON API v1.0 full support, 100% test coverage, APL2) https://github.com/neomerx/json-api feel free to contact me. I would be happy to help.

**Comment by jasonlewis** [comment]
#205 has now been merged. :smile:
