### ISSUE TITLE
Unable to fetch nested includes

### ISSUE THREAD

**Issue by JeanLucEsser** [thephpleague/fractal#238]
I'm going crazy with this, here is a simple example, I have 3 Transformers for my 3 Classes: Individu, Entite, Fonction. 

/individus?include=entites.fonctions returns an error I do not understand. Debugging shows that each include method is correctly called.

```php
class IndividuTransformer extends TransformerAbstract
{
    protected $availableIncludes = [
        'entites.fonctions'
    ];
    public function transform(Individu $individu)
    {
        return [
            'id' => (int) $individu['id']
        ];
    }
    public function includeEntites(Individu $individu)
    {
        return $this->collection($individu->entites, new EntiteTransformer());
    }
}
```

```php
class EntiteTransformer extends TransformerAbstract
{
    protected $availableIncludes = [
        'fonctions'
    ];
    public function transform(Entite $entite)
    {
        return [
            'id' => (int) $entite->id
        ];
    }
    public function includeFonctions(Entite $entite)
    {
        return $this->collection($entite->fonctions, new FonctionTransformer);
    }
}
```

```php
class FonctionTransformer extends TransformerAbstract
{
    public function transform(Fonction $fonction)
    {
        return [
            'id' => (int) $fonction->id
        ];
    }
}
```

Error is as follows:

ErrorException in TransformerAbstract.php line 177:
call_user_func() expects parameter 1 to be a valid callback, class 'App\Transformers\IndividuTransformer' does not have a method 'includeEntites.fonctions'

**Comment by JeanLucEsser** [comment]
Ok I found what I did wrong.

In my IndividuTransformerClass I should put:

```php
    protected $availableIncludes = [
        'entites', 'fonctions' // was 'entites.fonctions' before
    ];
```

Still, I won't close the issue as this doesn't feel right. This reads as "I need an includeFonctions method on my IndividuTransformer Class. Which is not the case.

**Comment by willishq** [comment]
I see what is wrong here and it seems you are confusing the loading of nested includes, you don't need to put `fonctions` in your `availableIncludes` parameter because it's not included on that transformer. Loading nested includes sounds difficult but it's really simple:

in your uri you specify with dot syntax:

`/individus?include=entites.fonctions`

This says "also load `entities` and load `foncions` from entities" so it will look in the respective transformers for the correct include, using the dot syntax only in the uri. This is intended behaviour.

**Comment by isneezy** [comment]
Never mind i found what i did wrong. It's `include` and not `includes` as I typed into the url.
