### ISSUE TITLE
Transform related object only if it's already available

### ISSUE THREAD

**Issue by Deleugpn** [thephpleague/fractal#270]
I'm just starting in the resourceful API world and I'd like feedback from the community on the following matter:

I have a TicketController:

```
	public function index($id = null) {
		$tickets = Ticket::with('interactions', 'user')->get();
		return $this->response->collection($tickets, new TicketTransformer());
	}
```

And my TicketTransform is kind like this

```
	public function transform(Ticket $ticket) {
		$array = [
			'id' => $ticket->id,
			'title' => $ticket->title,
			'status' => $this->transformerMessage($ticket->status)
		];
		if ($ticket->relationLoaded('user'))
			return array_merge($array, $this->user($ticket));
		return $array;
	}
```

The reason I have a ```$this->user``` method is because I'm trying to achieve is the include of relation models **ONLY IF THEY'RE AVAILABLE**. That is:

```
	public function user(Ticket $ticket) {
		$userTransform = new UserTransformer();
		return array('user' => $userTransform->transform($ticket->user));
	}
```

The bottom line is that now I can re-use my **TicketTransform** in cases that I don't want to include the **user** relationship without relying on the request. Which means that I decided that the **TicketController** will always load the **user model** by default (kind of like **defaultInclude**) but without tying up the transform class with this obligation. If by any means I need to transform **tickets** from somewhere else, **the user relation** will only be automatically transformed if it's already available through eager loading.

Can this be achieved differently using Fractal? Am I digging a bad practice here?

Thanks in advance.

**Comment by golonix** [comment]
If you're entering API world, I'd suggest to stick to some API standard. If you're using Fractal, you probably want to stick to JSON API standard, because Fracal provides JSON API serializer. Read about it.

As for your question, I wouldn't consider it a bad practice. It depends on your API, if and what standard do you want to keep and how API should behave.
However, as for your code, I'd use Fractal's includes functionality:
```php
public function transform(Ticket $ticket)
{
	return [
		'id' => $ticket->id,
		'title' => $ticket->title,
		'status' => $this->transformerMessage($ticket->status)
	];
}

public function includeUser(Ticket $ticket)
{
	if (null !== $ticket->user) { // or if($ticket->relationLoaded('user'))
		return $this->item($ticket->user, new UserTransformer())
	} 
}
```
Should this include be default or available? It is up to you and your needs.
Check out http://fractal.thephpleague.com/transformers/ (Including Data part).

**Comment by Deleugpn** [comment]
The problem with the include functionality of Fractal is that your request (the client's request, the consumer of the API) have to make the request (if available) OR I have to make it include every time by default.

My goal is to provide one single transformer that is capable of **nesting **the transformation of children IF AND ONLY IF the resource is already available.

In other words, if the controller loaded the **related resource** before delivering it to the transformer, I want that **related resource** to be transformed as well (by it's own transformer). But if in some other controller I'm using the same resource, the same transformer **BUT** I did not load the **related** resource, the transformer won't do any extra work at all.

**Comment by golonix** [comment]
> My goal is to provide one single transformer that is capable of nesting the transformation of children IF AND ONLY IF the resource is already available.

You can achieve that by using includes functionality (default include) and this `if` statement that you're talking about. Like I wrote, I wouldn't consider using ifs a bad practice, however, I'd try to avoid it. I think, better approach is to use includes and return `null` for include if given related resource is not loaded.

**Comment by willishq** [comment]
I would second @golonix on this, to be honest. Not giving the API user control over what gets returned is dangerous, when they make the request they should be able to request the data, it's not your API's responsibility to decide what relationships to include based on lazy-loaded resources, these should be requested by the client.

Of course, I'm not telling you how to write your API but consider this: given that the data you return then becomes variable depending on the pre-loaded resources, how does your API consumer handle this? Are they expecting it? If so, they can request the resources they're expecting.

If they're not expecting it then you might need to think about the design of your API in order to make it easier to use.

**Comment by chillyistkult** [comment]
It has actually nothing todo if the API user should have control over what gets returned or not. Lazy-loading is just terrible slow in some cases so we want to eager-load the data before we call the transformer (but of course still want to transform the response). So is there a way to use transformers with eager-loaded data or not?
