### ISSUE TITLE
Impossible to override self link in Transformer when using JsonApiSerializer

### ISSUE THREAD

**Issue by Belphemur** [thephpleague/fractal#420]
Hello,

When using the JSON API Serializer, I cannot override the self url because of the way the array_merge is done.

To be able to override the generated self link, the array_merge should be inverted
# From
https://github.com/thephpleague/fractal/blob/17b53e8bb8bc72046c8a71a1f4dbc6acc4db1d72/src/Serializer/JsonApiSerializer.php#L90
# To
```php
 $resource['data']['links'] = array_merge($resource['data']['links'], $custom_links);
```

This way the user can (if he desires) override the generate self link.

I want to do this because I'm using object that have parents leading to url like: /orgs/{org}/users/{user} and I cannot afford to set the base url for the serializer before each transformer call.

**Comment by greydnls** [comment]
I believe this would be a breaking change, as it could possibly effect output for people who are currently using the existing functionality. 

Are you able to set the base url for the serializer when you set it on the manager?

**Comment by huoding** [comment]
I have same question!

**Comment by biggator** [comment]
This should **not** be considered a breaking change because including a "self" link in the data implies that it should override any default "self" link built into the JasonApiSerializer. If you don't want to serialize the custom "self" link, then don't include it in the transformer.

Setting a baseUrl (if possible, but not in my case) seems like an onerous workaround. I believe that the baseUrl is best considered a constant for the api.

This is a bug. Fixing it as @Belphemur suggests could also solve the feature requested in issue #400.

**Comment by hongaar** [comment]
I agree with @biggator here.

Whoever is currently using the `self` key in custom links in transformers should not be surprised to see their implementations _break_, although in this case it would be more appropriate to say their implementations would _finally work_, as that `self` key they're using is currently completely ignored.

On a slightly different note, this PR would help solve #400 only in part, as it doesn't provide a way to set custom links in `relationships` data.

**Comment by hongaar** [comment]
nvmd. didn't see the PR 😕
