### ISSUE TITLE
Primitive includes don't work with JsonApiSerializer

### ISSUE THREAD

**Issue by nmoskovkinmp** [thephpleague/fractal#461]
I use the version 0.17.0 and  my transformer has code like that

```
public function includeAssigned($course)
{
       return $this->primitive((int)$course['assigned']);
}
```

Every time I try to serialize my data I get an exception
If I use another serializer say ArraySerializer I will get normal result.

```
Warning: array_key_exists() expects parameter 2 to be array, integer given in /var/www/l***/vendor/league/fractal/src/Serializer/JsonApiSerializer.php:316
#0 /var/www/***/vendor/league/fractal/src/Serializer/JsonApiSerializer.php(182): League\Fractal\Serializer\JsonApiSerializer->isNull(1)
```

**Comment by KorvinSzanto** [comment]
Primitives don't work with the `JsonApiSerializer` because this serializer requires the transformed values to match a specific format so that they can appropriately be packed into the jsonapi format.

A proper transformed data array will look like this:
```
[
  'id' => 1
]
```

And of course a primitive shouldn't ever look like this. Instead just use an `Item` instance:

```
public function includeAssigned($course)
{
    return $this->item(['id' => $course['assigned'], function($data) { return $data; }, 'course');
}
```

----

That all said, we could change the `JsonApiSerializer` to just use the primitive type data as the ID by default, but I'd argue that that is a little confusing.
